# Generated by Django 5.1.7 on 2025-03-23 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_author_name', models.BooleanField(default=False)),
                ('hide_author_email', models.BooleanField(default=False)),
                ('hide_title', models.BooleanField(default=False)),
                ('hide_submission_date', models.BooleanField(default=False)),
                ('anonymized_file', models.FileField(blank=True, null=True, upload_to='anonymized/')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anonymization_settings', to='articles.article')),
            ],
        ),
    ]
