# Generated by Django 5.1.7 on 2025-03-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_subject_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='anonymized_file',
            field=models.FileField(blank=True, null=True, upload_to='anonymized_pdfs/'),
        ),
    ]
