# Generated by Django 5.1.7 on 2025-03-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_anonymized_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deanonymized_file',
            field=models.FileField(blank=True, null=True, upload_to='deanonymized_pdfs/'),
        ),
    ]
