# Generated by Django 5.1.7 on 2025-03-28 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_deanonymized_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('received', 'Makale Geldi'), ('assigned', 'Hakeme Atandı'), ('replied', 'Hakem Cevap Verdi'), ('published', 'Yayınlandı')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='articles.article')),
            ],
        ),
    ]
