# Generated by Django 5.1.7 on 2025-03-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articlelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_email',
            field=models.EmailField(max_length=254, verbose_name='E-posta Adresi'),
        ),
    ]
