# Generated by Django 5.1.7 on 2025-03-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='revised_file',
            field=models.FileField(blank=True, null=True, upload_to='revised_pdfs/'),
        ),
    ]
