# Generated by Django 5.1.7 on 2025-03-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_revised_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
